In [3]:
# Let's test our theory to do hamming (16,11) with numpy
# Run this block first to call numpy in.
import numpy as np # this is how you call a python library


#### Numpy array quick intro

#### Build numpy array and check its spec

In [ ]:
# In numpy, the data array is np.array
list = [1,2,3,4]            # this is a python list, or a "python number array"
array = np.array([1,2,3,4]) # this is a numpy array, or a "numpy number array"
print(type(list))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])
print(array_1.ndim)                   # ndim is to check dimension
print(array_2.ndim)
## TODO: Can we check the dimension of a regular phyton list?

1
2


In [6]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])

print(array_1.shape)                  # shape is to check the size of each dimension
print(array_2.shape)

(4,)
(4, 1)


In [7]:
array_2b = np.array([[1],
                     [2],
                     [3],
                     [4]])            # a 4x1 array in this kind of viual might be more intuitive?
print(array_2b.shape)
#print(array_2b.ndim)

(4, 1)


#### Create an empty numpy array or a special array:

In [9]:
# create empty four lanes in one line of code:
I380_16A = np.zeros((4, 10), dtype=int)

print("I380 exit 16A:")
print(I380_16A)

I380 exit 16A:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [10]:
# We can also create a special kind of array with eye:
Special_array_1 = np.eye(4, 4, dtype=int)
print(Special_array_1)

Special_array_2 = np.eye(4, 8, dtype=int)
print(Special_array_2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


#### Matrix multiply and numpy

In math, a matrix is a box of number arranged in rows and columns, for example:

\begin{bmatrix} 1 & 2 & 3 \\ 10 & 20 & 30 \end{bmatrix}

Matrix math, how does it work: multiply, matrix multiply



In math:
To explain matrix multiple is shitty: $P_{i,j} = \sum_{k=1}^n{Q_{i,k} \times R_{k,j}}$

Or this:

$P =
\begin{bmatrix}
Q_{11} R_{11} + Q_{12} R_{21} + \cdots + Q_{1n} R_{n1} &
  Q_{11} R_{12} + Q_{12} R_{22} + \cdots + Q_{1n} R_{n2} &
    \cdots &
      Q_{11} R_{1q} + Q_{12} R_{2q} + \cdots + Q_{1n} R_{nq} \\
Q_{21} R_{11} + Q_{22} R_{21} + \cdots + Q_{2n} R_{n1} &
  Q_{21} R_{12} + Q_{22} R_{22} + \cdots + Q_{2n} R_{n2} &
    \cdots &
      Q_{21} R_{1q} + Q_{22} R_{2q} + \cdots + Q_{2n} R_{nq} \\
  \vdots & \vdots & \ddots & \vdots \\
Q_{m1} R_{11} + Q_{m2} R_{21} + \cdots + Q_{mn} R_{n1} &
  Q_{m1} R_{12} + Q_{m2} R_{22} + \cdots + Q_{mn} R_{n2} &
    \cdots &
      Q_{m1} R_{1q} + Q_{m2} R_{2q} + \cdots + Q_{mn} R_{nq}
\end{bmatrix}$



I think using an example is better:

$E = AD = \begin{bmatrix}
  10 & 20 & 30 \\
  40 & 50 & 60
\end{bmatrix}
×
\begin{bmatrix}
  2 & 3 & 5 & 7 \\
  11 & 13 & 17 & 19 \\
  23 & 29 & 31 & 37
\end{bmatrix} =
\begin{bmatrix}
  930 & 1160 & 1320 & 1560 \\
  2010 & 2510 & 2910 & 3450
\end{bmatrix}$

$M3 = M1×M2 = \begin{bmatrix}
  a_{1}  & b_{1} \\
  c_{1}  & d_{1}
\end{bmatrix}
×
\begin{bmatrix}
  a_{2}  & b_{2} \\
  c_{2}  & d_{2}
\end{bmatrix} =
\begin{bmatrix}
  a_{1}×a_{2}+b_{1}×c_{2} & a_{1}×b_{2}+b_{1}×d_{2}\\
  c_{1}×a_{2}+d_{1}×c_{2} & c_{1}×b_{2}+d_{1}×d_{2}
\end{bmatrix}$

So, a [2,3] x [3,4] = [2,4]

And a [1,3] x [2,4] is not "mathematically legal".

#### How it's done in numpy?

In [12]:
# numpy use ".dot" or "@" as "X" in matrix multiple
# The syntax is Matrix A .dot (Matrix B)
# or Matrix A @ Matrix B
Matrix_A = np.array([
    [1,2,3],
    [0,1,2]
])

Matrix_B = np.array([
    [1,0,0,0],
    [1,1,1,1],
    [0,1,2,3],
])

print (Matrix_A .dot (Matrix_B))    # this is how to use .dot
print (Matrix_A @ Matrix_B)         # this is how to use @
# which one would you prefer?

[[ 3  5  8 11]
 [ 1  3  5  7]]
[[ 3  5  8 11]
 [ 1  3  5  7]]


In [13]:

Matrix_A = np.array([
    [1, 2, 3, 4],

])

Matrix_B = np.array([
    [1],
    [2],
    [3],
    [4]
])

print (Matrix_A @ Matrix_B) # what would happen?
print (Matrix_B @ Matrix_A) # what would happen?

[[30]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


### That's "good enough" math and matrix for ya. Let's reconsider Hamming (16,11):


11 bits in

16 bits out

So instead of double for loops, we can do matrix operation to get it in one go?

[1,11] x [?] = [1,16]?

#### We need an i X j matrix to make it work.

In [17]:
## TODO: test all these: check the shape of input; print input, matrix_I, and output; check the shape of output.
input_1 = np.array([
    [1, 2, 3, 4]]
)

#print (input_1.shape)

matrix_I = np.eye (4)
output_1 = input_1 @ matrix_I

print (input_1)
#print (matrix_I)

print (output_1)
#output.shape

[[1 2 3 4]]
[[1. 2. 3. 4.]]


In [19]:
## TODO: understand this matrix operation
input = np.array([
    [1, 2, 3, 4]])
Operation_I = np.array ([  # this matrix can also be done with a simply line: Operation_I = np.eye (4)
    [1,0,0,0,0],
    [0,1,0,0,1],
    [0,0,1,0,1],
    [0,0,0,1,1],
])

output = input @ Operation_I

print ("shape check of input:")
print (input.shape)
print ("shape check of operation matrix:")
print (Operation_I.shape)
print ("shape check of output matrix:")
print (output.shape) ## TODO: what is the meaning of this?
print ("this is the output:")
print (output)

# 9 = 2+3+4

shape check of input:
(1, 4)
shape check of operation matrix:
(4, 5)
shape check of output matrix:
(1, 5)
this is the output:
[[1 2 3 4 9]]


In [36]:
# So that's how we can do Hamming (16,11) in numpy!
# 1) We need a 11x16 matrix

#     data    "P1-P4"    "P_0"
# 2) [1,11] x [11,5] X [15,16]= [1,16]

# 3) The output 16 bits = 11 bits of input data + 5 bits of parity checks
# 3.1) The frist [11,5] "G_1 matrix" (I1|P1)
I_1 = np.eye(11, dtype=int) # we define data tyep to int so we save some storage (default number type in numpy is over-kill for this application)
## TODO: encoding P1-P4, and P0 based on our theory, our SoS matrix:
# P1 checks: D1, D2, D4, D5, D7, D9, D11
# P2 checks: D1, D3, D4, D6, D7, D10, D11
# P3 checks: D2, D3, D4, D8, D9, D10, D11
# P4 checks: D5, D6, D7, D8, D9, D10, D11
P_1 = np.array([
  # P1 P2 P3 P4
    [1, 1, 0, 0],  #D1
    [1, 0, 1, 0],  #D2
    [0, 1, 1, 0],  #D3
    [1, 1, 1, 0],  #D4
    [1, 0, 0, 1],  #D5
    [0, 1, 0, 1],  #D6
    [1, 1, 0, 1],  #D7
    [0, 0, 1, 1],  #D8
    [1, 0, 1, 1],  #D9
    [0, 1, 1, 1],  #D10
    [1, 1, 1, 1],  #D11
])
G_1 = np.concatenate((I_1, P_1), axis=1)  # this is just a simple function to stich two matrix together
# print (G_1)

#3.2 now let's do a [15,16] "G_2 matrix" (I2|P0)
I_2 = np.eye(15, dtype=int)
# print (I_2)
P_0 = np.ones((15, 1), dtype=int) # total parity check P0 is going to Sum all the bits (d1-d11, P1-P4)
G_2 = np.concatenate((I_2, P_0), axis=1)
# print (G_2)

#3.2 the ultimate generator matrix [11,5] X [15,16] = [11,16]
G = G_1 @ G_2 %2
print ("The generator matrix:")
print (G)


The generator matrix:
[[1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]]


In [34]:
# 4) Then we can generate our [1,16] output
Input = np.array([[1,0,1,1,0,0,1,1,0,1,0]])
Output = Input @ G
print ("The output of the generator matrix:")
print (Output)
# In output, the last five bits are not quite parity check yet, they are the sum
# So let's do modulo 2

Hamming_code = Output % 2

print ("Converted to extended hamming code:")
print (Hamming_code)

The output of the generator matrix:
[[1 0 1 1 0 0 1 1 0 1 0 3 5 4 3 3]]
Converted to extended hamming code:
[[1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1]]


#### What about error checking then?
It's just to turn a [1,16] to a [1,5] right?
So a [16,5] matrix can turn the output into an error code, in theory

In [39]:
# this error checking code, is basically your P matrix sitting on top of a (5x5) "eye" matrix

#We just need the "non-eye" part of the generator matrix (why?)
#                       -------------
#                       |This part  |
#[[1 0 0 0 0 0 0 0 0 0 0|1 1 0 0 1] |
# [0 1 0 0 0 0 0 0 0 0 0|1 0 1 0 1] |
# [0 0 1 0 0 0 0 0 0 0 0|0 1 1 0 1] |
# [0 0 0 1 0 0 0 0 0 0 0|1 1 1 0 0] |
# [0 0 0 0 1 0 0 0 0 0 0|1 0 0 1 1] |
# [0 0 0 0 0 1 0 0 0 0 0|0 1 0 1 1] |
# [0 0 0 0 0 0 1 0 0 0 0|1 1 0 1 0] |
# [0 0 0 0 0 0 0 1 0 0 0|0 0 1 1 1] |
# [0 0 0 0 0 0 0 0 1 0 0|1 0 1 1 0] |
# [0 0 0 0 0 0 0 0 0 1 0|0 1 1 1 0] |
# [0 0 0 0 0 0 0 0 0 0 1|1 1 1 1 1]]|
#                       |This part  |
#                       -------------
H_T = np.array([
    [1, 1, 0, 0, 1],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 0, 1],
    [1, 1, 1, 0, 0],
    [1, 0, 0, 1, 1],
    [0, 1, 0, 1, 1],
    [1, 1, 0, 1, 0],
    [0, 0, 1, 1, 1],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]
])

print (H_T.shape)

(16, 5)


In [40]:
# next we just repeat the hamming coding trick, but on [1,16] output
# output_code: [[1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1]]
# you can inject 1 bit error below, anywhere:
received_msg = [[1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1]]
Error_msg = received_msg @ H_T % 2
print ("the error code:")
print (Error_msg)

## TODO: wait, the postion code how?

the error code:
[[0 0 0 0 0]]
