In [ ]:
import numpy as np
# Let's use numpy to do hamming faster



### Numpy array quick intro

#### Build numpy array and check its spec

In [ ]:
# In numpy, the data array is np.array
list = [1,2,3,4]            # this is a python list, or a "python number array"
array = np.array([1,2,3,4]) # this is a numpy array, or a "numpy number array"
print(type(list))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])
print(array_1.ndim)                   # ndim is to check dimension
print(array_2.ndim)
## TODO: Can we check the dimension of a regular phyton list?

1
2


In [ ]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])

print(array_1.size)                   # size is to check the total number of elements
print(array_2.size)

4
4


In [ ]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])

print(array_1.shape)                  # shape is to check the size of each dimension
print(array_2.shape)

(4,)
(4, 1)


In [ ]:
array_2b = np.array([[1],
                     [2],
                     [3],
                     [4]])            # a 4x1 array in this kind of viual might be more intuitive?
print(array_2b.shape)
#print(array_2b.ndim)

(4, 1)


In [ ]:
array_3 = array_2.reshape(1, 4)       # reshape can reshape an array
print(array_3)
print(array_3.shape)

## TODO: check what would happen if we reshape array_2 to 2x2? 2x3?

[[1 2 3 4]]
(1, 4)


In [ ]:
## TODO: make a 3D array with the size of 4
## TODO: make a 4D array with the size of 4
## TODO: make a 4D array with the size of 3

#### Create an empty numpy array and populate it with numbers:

In [ ]:
# create empty four lanes in one line of code:
I380_16A = np.zeros((4, 10), dtype=int)

print("I380 exit 16A:")
print(I380_16A)

I380 exit 16A:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
# let's put some cars in the lanes
# the following examples are just different ways we can assign values to each matrix by indexing
I380_16A[0,1] = 1
I380_16A[1,2:6] = 1
I380_16A[2,1:5] = I380_16A[1,2:6]
print("I380 exit 16A, active traffic:")
print(I380_16A)

I380 exit 16A, active traffic:
[[0 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
# We can also create a special kind of array with eye:
I380_16B = np.eye(4, 4, dtype=int)
print(I380_16B)

I380_16C = np.eye(4, 10, dtype=int)
print(I380_16C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]]


### Number arrays, matrix and linear algebra

#### In math, a matrix is a box of number arranged in rows and columns, for example:

\begin{bmatrix} 1 & 2 & 3 \\ 10 & 20 & 30 \end{bmatrix}

In [ ]:
# How do you define such matrix in numpy? With number arrays, off course!
Matrix_1 = np.array([
    [1,2,3],
    [10,20,30]
])

## TODO: check its dimension, size, and shape


In [ ]:
# Can you index this matrix?
# Try to find the index of "30" in Matrix_1
Matrix_1[i,j]  ## TODO replace i and j with the index number of "30"

NameError: name 'i' is not defined

#### Matrix math, how does it work: addition

In math: if two matrices are excatly the same size (Q is 2x2, and R is 2x2), they can be added together *elementwise*:  $S_{i,j} = Q_{i,j} + R_{i,j}$

$S =
\begin{bmatrix}
  Q_{11} + R_{11} & Q_{12} + R_{12} \\
  Q_{21} + R_{21} & Q_{22} + R_{22} \\
\end{bmatrix}$

In [ ]:
# In numpy:
Q = np.array([
    [1,2],
    [3,4]
])

R = np.array([
    [10,20],
    [30,40]
])

Q+R

array([[11, 22],
       [33, 44]])

In [ ]:
# In numpy, what if two matrix is not the same size?
Q = np.array([
    [1],
])

R = np.array([
    [10,20],
    [30,40]
])


Q+R

# This is not linear algebra legal, but relaxed in the so called "NumPy’s broadcasting rule"

array([[11, 21],
       [31, 41]])

In [ ]:
# Let's test the limit of this broadcasting rule (1/5):

Q = 1 # What if Q is a number?

R = np.array([
    [10,20],
    [30,40]
])


Q+R

array([[11, 21],
       [31, 41]])

In [ ]:
# Let's test the limit of this broadcasting rule (2/5):

Q = 3.14 # What if Q is different number type?

R = np.array([
    [10,20],
    [30,40]
])


Q+R

array([[13.14, 23.14],
       [33.14, 43.14]])

In [ ]:
# Let's test the limit of this broadcasting rule (3/5):

Q = [1,2] # What if Q is a list (number array in vanilla python)?

R = np.array([
    [10,20],
    [30,40]
])


Q+R

array([[11, 22],
       [31, 42]])

In [ ]:
# Let's test the limit of this broadcasting rule (4/5):

Q = "1"       # what if Q is a diffrent data type?
R = np.array([
    [10,20],
    [30,40]
])


Q+R

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('int64')) -> None

In [ ]:
# Let's test the limit of this broadcasting rule (5/5):

Q = np.array([      # what if Q is a slightly bigger numpy array?
    [1,2,3],
    [4,5,6]
])

R = np.array([
    [10,20],
    [30,40]
])

Q+R

#### Matrix math, how does it work: multiply, scalar multiply

In math:
A matrix $M$ can be multiplied by a scalar $\lambda$. The result is noted $\lambda M$, and it is a matrix *elementwisely* multiplied by $\lambda$:

$\lambda M =
\begin{bmatrix}
  \lambda \times M_{11} & \lambda \times M_{12} \\
  \lambda \times M_{21} & \lambda \times M_{22} \\
\end{bmatrix}$

A more concise way of writing this is:

$(\lambda M)_{i,j} = \lambda (M)_{i,j}$

In [ ]:
# in numpy, we use *
M = np.array([
    [1,2],
    [3,4]
])

l = 10

print (l * M)
print (M * l)

[[10 20]
 [30 40]]
[[10 20]
 [30 40]]


In [ ]:
## TODO: Try different types of "l" untill numpy broke
M = np.array([
    [1,2],
    [3,4]
])

l = [10,20]

print (l * M)


[[10 40]
 [30 80]]


#### Matrix math, how does it work: multiply, matrix multiply



In math:
To explain matrix multiple is shitty: $P_{i,j} = \sum_{k=1}^n{Q_{i,k} \times R_{k,j}}$

Or this:

$P =
\begin{bmatrix}
Q_{11} R_{11} + Q_{12} R_{21} + \cdots + Q_{1n} R_{n1} &
  Q_{11} R_{12} + Q_{12} R_{22} + \cdots + Q_{1n} R_{n2} &
    \cdots &
      Q_{11} R_{1q} + Q_{12} R_{2q} + \cdots + Q_{1n} R_{nq} \\
Q_{21} R_{11} + Q_{22} R_{21} + \cdots + Q_{2n} R_{n1} &
  Q_{21} R_{12} + Q_{22} R_{22} + \cdots + Q_{2n} R_{n2} &
    \cdots &
      Q_{21} R_{1q} + Q_{22} R_{2q} + \cdots + Q_{2n} R_{nq} \\
  \vdots & \vdots & \ddots & \vdots \\
Q_{m1} R_{11} + Q_{m2} R_{21} + \cdots + Q_{mn} R_{n1} &
  Q_{m1} R_{12} + Q_{m2} R_{22} + \cdots + Q_{mn} R_{n2} &
    \cdots &
      Q_{m1} R_{1q} + Q_{m2} R_{2q} + \cdots + Q_{mn} R_{nq}
\end{bmatrix}$



I think using an exampel is better:

$E = AD = \begin{bmatrix}
  10 & 20 & 30 \\
  40 & 50 & 60
\end{bmatrix}
×
\begin{bmatrix}
  2 & 3 & 5 & 7 \\
  11 & 13 & 17 & 19 \\
  23 & 29 & 31 & 37
\end{bmatrix} =
\begin{bmatrix}
  930 & 1160 & 1320 & 1560 \\
  2010 & 2510 & 2910 & 3450
\end{bmatrix}$

$M3 = M1×M2 = \begin{bmatrix}
  a_{1}  & b_{1} \\
  c_{1}  & d_{1}
\end{bmatrix}
×
\begin{bmatrix}
  a_{2}  & b_{2} \\
  c_{2}  & d_{2}
\end{bmatrix} =
\begin{bmatrix}
  a_{1}×a_{2}+b_{1}×c_{2} & a_{1}×b_{2}+b_{1}×d_{2}\\
  c_{1}×a_{2}+d_{1}×c_{2} & c_{1}×b_{2}+d_{1}×d_{2}
\end{bmatrix}$

So, a [2,3] x [3,4] = [2,4]

And a [1,3] x [2,4] is not mathly legal.

In [ ]:
# numpy use ".dot" or "@" as "X" in matrix multiple
# The syntax is Matrix A .dot (Matrix B)
# or Matrix A @ Matrix B
Matrix_A = np.array([
    [10,20,30],
    [40,50,60]
])

Matrix_B = np.array([
    [2,3,5,7],
    [11,13,17,19],
    [23,29,31,37],
])

print (Matrix_A .dot (Matrix_B))    # this is how to use .dot
print (Matrix_A @ Matrix_B)         # this is how to use @
# which one would you prefer?

[[ 930 1160 1320 1560]
 [2010 2510 2910 3450]]
[[ 930 1160 1320 1560]
 [2010 2510 2910 3450]]


In [ ]:
## TODO: let's try to break numpy again:
Matrix_A = np.array([
    [1, 2, 3, 4],

])

Matrix_B = np.array([
    [1],
    [2],
    [3],
    [4]
])

print (Matrix_A @ Matrix_B) # what would happen?
print (Matrix_B @ Matrix_A) # what would happen?

[[30]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
## TODO: let's try to break numpy again:
Matrix_A = np.array([
    [10,20,30],
    [40,50,60]
])

Matrix_B = np.array([
    [2,3,5,7],
    [11,13,17,19],
    [23,29,31,37],
])

Matrix_B @ (Matrix_A) # what would happen?

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
## TODO: let's try to break numpy again:
Matrix_A = np.array([
    [10,20],

])

Matrix_B = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
])

Matrix_A .dot (Matrix_B) # what would happen?

In [ ]:
## TODO: let's try to break numpy again:
Matrix_A = np.array([
    [10],

])

Matrix_B = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
])

Matrix_A @ Matrix_B # what would happen?

### That's enough math and matrix for ya. Let's reconsider Hamming (16,11):

11 bits in

16 bits out

So instead of double for loops, we can do matrix operation to get it in one go?


[1,11] x [?] = [1,16]?

#### We need an i X j matrix to make it work.

In [ ]:
## TODO: test all these: check the shape of input; print input, matrix_I, and output; check the shape of output.
input_1 = np.array([
    [1, 2, 3, 4]]
)

# print (input.shape)

matrix_I = np.eye (4)
output_1 = input_1 @ matrix_I

print (input_1)
#print (matrix_I)

print (output_1)
#output.shape

[[1 2 3 4]]
[[1. 2. 3. 4.]]


In [ ]:
## TODO: what is the difference between this input and the one above?
## TODO: what is the differenfe between this output and the one above?

input_2 = np.array(
    [1, 2, 3, 4]
)

# print (input.shape)

matrix_I = np.eye (4)
output_2 = input_2 @ matrix_I

print (input_2)
#print (matrix_I)

print (output_2)
#output.shape

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
## TODO: understand this matrix operation
input = np.array([
    [1, 2, 3, 4]])
Operation_I = np.array ([
    [1,0,0,0,0],
    [0,1,0,0,1],
    [0,0,1,0,1],
    [0,0,0,1,1],
])

output = input @ Operation_I

print ("shape check of input:")
print (input.shape)
print ("shape check of operation matrix:")
print (Operation_I.shape)
print ("shape check of output matrix:")
print (output.shape) ## TODO: what is the meaning of this?
print ("this is the output:")
print (output)

# 9 = 2+3+4

shape check of input:
(1, 4)
shape check of operation matrix:
(4, 5)
shape check of output matrix:
(1, 5)
this is the output:
[[1 2 3 4 9]]


In [ ]:
# So that's how we can do Hamming (16,11) in numpy!
# 1) We need a 11x16 matrix
# 2) [1,11] x [11,16] = [1,16]
# 3) The output 16 bits = 11 bits of input data + 5 bits of parity checks
# 3.1) this transformation matrix has too components (I|P)
I = np.eye(11, dtype=int) # we define data tyep to int so we save some storage (default number type in numpy is over-kill for this application)


P = np.array([
  # P1 P2 P3 P4 P0
    [1, 1, 0, 0, 1], # D1 encoded with 0b0011 = 3
    [1, 0, 1, 0, 1], # D2 encoded with 0b0101 = 5
    [0, 1, 1, 0, 1], # D3...                    6
    [1, 1, 1, 0, 0], # D4...                    7 but why this P0 is 0?
    [1, 0, 0, 1, 1], # D5...                    9
    [0, 1, 0, 1, 1],
    [1, 1, 0, 1, 0], # D7...                      but why this P0 is 0?
    [0, 0, 1, 1, 1],
    [1, 0, 1, 1, 0], # D9...                      but why this P0 is 0?
    [0, 1, 1, 1, 0], # D10...                     but why this P0 is 0?
    [1, 1, 1, 1, 1]
])

#print (I)
#print (P)

G = np.concatenate((I, P), axis=1)  # this is just a simple function to stich two matrix together
print (G)



[[1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]]


In [ ]:
Input = np.array([[1,0,1,1,0,0,1,1,0,1,0]])
Input @ P

array([[3, 5, 4, 3, 6]])

In [ ]:
# 4) Then we can generate our [1,16] output
Input = np.array([[1,0,1,1,0,0,1,1,0,1,0]])
Output = Input @ G
print ("The output of the generator matrix:")
print (Output)
# In output, the last five bits are not quite parity check yet, they are the sum
# So let's do modulo 2

Hamming_code = Output % 2

print ("converted to extended hamming code:")
print (Hamming_code)

The output of the generator matrix:
[[1 0 1 1 0 0 1 1 0 1 0 3 5 4 3 3]]
converted to extended hamming code:
[[1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1]]


#### What about error checking then?
It's just to turn a [1,16] to a [1,5] right?
So a [16,5] matrix can turn the output into an error code, in theory.

Please check the in class notebook see how it's done.

#### But what about XOR? Isn't bitwise operation faster?


Actually, no. Numpy is written in C and optimized for arithmatic operation.

It's so fast that its modulo 2 is faster than bitwise ^.

The following code will show you the speed difference.

In [ ]:
import numpy as np
import timeit

# --- Setup ---
# 11 data bits, 16 total codeword bits
G = np.random.randint(0, 2, size=(11, 16)) # this is a fake transfer matrix
d = np.array([[1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1]]) # this is a fake data input

# Method A: Matrix Multiplication + Modulo
def method_modulo():
    return (d @ G) % 2       # this will generate a fake hamming output by %2

# Method B: Bitwise AND + XOR Reduction
def method_xor():
    # d.T & G creates an (11,16) matrix where each row is d[i] AND G[i]
    # bitwise_xor.reduce then XORs all 11 rows together
    return np.bitwise_xor.reduce(d.T & G, axis=0) # this will generate a fake hamming output by xor

# --- Execution ---
n = 10000
time_modulo = timeit.timeit(method_modulo, number=n)
time_xor = timeit.timeit(method_xor, number=n)

print(f"Results over {n} iterations:")
print(f"Matrix Mult (% 2): {time_modulo:.4f} seconds")
print(f"Bitwise XOR:       {time_xor:.4f} seconds")

Results over 10000 iterations:
Matrix Mult (% 2): 0.0591 seconds
Bitwise XOR:       0.0934 seconds
