#### 1) Vanilla Python Basics: Data Types & Indexing

In [9]:
# 1. Check data and element types
data_list = [1, 1, 0, 0, 0, 1]
print(type(data_list)) # <class 'list'>
print(type(data_list[0])) # <class 'int'>

<class 'list'>
<class 'int'>


In [5]:
# 2. Update an element in a list (Mutable)
test_array = [0, 0, 0, 0, 0]
test_array[2] = 1
print(test_array) # [0, 0, 1, 0, 0]



[0, 0, 1, 0, 0]


In [8]:
# 3. Fast array creation trick
empty_16_bit = [0] * 16
print(empty_16_bit)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


#### 2) Iteration: Loops & enumerate

In [10]:

# 1. Range with steps (Start at, Stop before, Step size)
# Print 1, 3, 5, 7, 9
for i in range(1, 10, 2):
    print(i)



1
3
5
7
9


In [11]:
# 2. Nested loops
for i in "abc":
    for j in range(3):
        print(i, end="") # output: aaabbbccc



aaabbbccc

In [13]:
# 3. Using Enumerate for look-up tables
data_index = [3, 5, 6, 7]
for i, item in enumerate(data_index):
    print(f"Data index {i} has value {item}") # fancy printf to show index and value

Data index 0 has value 3
Data index 1 has value 5
Data index 2 has value 6
Data index 3 has value 7


#### 3) Bitwise Operations (Logic operation of numbers)

In [16]:
# 1. XOR operation (^)
print(0b1 ^ 0b1) # 0
print(0b1 ^ 0b0) # 1
print(2 ^ 6)     # 4



0
1
4


In [21]:
# 2. AND operation (&) for parity checking
# Check if bit 'i' is covered by parity 'p'
p = 2
i = 3
if (p & i) == p:
    print("Parity bit P2 checks this data bits")
else:
    print("Parity bit P2 doesn't check this data bits")

Parity bit P2 checks data bits D1


#### 4) NumPy: Array Creation & Shaping

In [40]:
import numpy as np

# 1. Create special arrays
empty_lanes = np.zeros((4, 10), dtype=int)
full_lanes = np.ones((4, 10), dtype=int)
identity_matrix = np.eye(4, dtype=int)

print ("empty lanes:")
print (empty_lanes)
print ("full lanes:")
print (full_lanes)
print ("identity matrix:")
print (identity_matrix)

empty lanes:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
full lanes:
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
identity matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [26]:
# 2. Check array specifications
array_2d = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(array_2d.ndim)  # Dimensions: 2
print(array_2d.shape) # Shape: (4, 1)
print(array_2d.size)  # Total elements: 4



2
(4, 1)
4


In [32]:
# 3. Reshape arrays
flat_array = array_2d.reshape(1, 4)
print (flat_array)
print(flat_array.ndim)  # Dimensions: 2
print(flat_array.shape) # Shape: (1,4)
print(flat_array.size)  # Total elements: 4

[[1 2 3 4]]
2
(1, 4)
4


#### 5) NumPy: Matrix Math

In [38]:
Matrix_A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Matrix_B = np.array([
    [1, 1],
    [1, 0],
    [1, 1]
])

# 1. Scalar multiplication (Element-wise)
print(Matrix_A * 10)

# 2. Matrix Multiplication using '@'
# [2x3] @ [3x2] = [2x2]
Result = Matrix_A @ Matrix_B
print (Result)

[[10 20 30]
 [40 50 60]]
[[ 6  4]
 [15 10]]


6) #### Traffic collsion check and car shifting

In [46]:
Fifteenth_ST = [0, 0, 1, 0, 0]
Sixth_AVE =    [0, 0, 1, 0, 0]

# 1. Collision Check Algorithm
def collision_check(lane_x, lane_y):
    for i in range(len(lane_x)):
        if lane_x[i] == 1 and lane_y[i] == 1:
            print(f"Collision at timepoint [{i}]!")

collision_check(Fifteenth_ST, Sixth_AVE)

# 2. Array Shifting (Traffic Delay)
# Shift the '1' one tick backward using pop/insert
test_lane = [0, 0, 1, 0, 0]
test_lane.insert(0, 0) # Insert empty space at start
test_lane.pop()        # Remove last element to maintain length

print (test_lane)

Collision at timepoint [2]!
[0, 0, 0, 1, 0]


#### 7) For hamming encoding, create a generator matrix (G) for hamming (16, 11) extended encoding:

In [48]:
import numpy as np

# 1) We need a 11x16 matrix

#     data    "P1-P4"    "P_0"
# 2) [1,11] x [11,5] X [15,16]= [1,16]

# 3) The output 16 bits = 11 bits of input data + 5 bits of parity checks
# 3.1) The frist [11,5] "G_1 matrix" (I1|P1)
I_1 = np.eye(11, dtype=int) # we define data tyep to int so we save some storage (default number type in numpy is over-kill for this application)
## TODO: encoding P1-P4, and P0 based on our theory, our SoS matrix:
# P1 checks: D1, D2, D4, D5, D7, D9, D11
# P2 checks: D1, D3, D4, D6, D7, D10, D11
# P3 checks: D2, D3, D4, D8, D9, D10, D11
# P4 checks: D5, D6, D7, D8, D9, D10, D11
P_1 = np.array([
  # P1 P2 P3 P4
    [1, 1, 0, 0],  #D1
    [1, 0, 1, 0],  #D2
    [0, 1, 1, 0],  #D3
    [1, 1, 1, 0],  #D4
    [1, 0, 0, 1],  #D5
    [0, 1, 0, 1],  #D6
    [1, 1, 0, 1],  #D7
    [0, 0, 1, 1],  #D8
    [1, 0, 1, 1],  #D9
    [0, 1, 1, 1],  #D10
    [1, 1, 1, 1],  #D11
])
G_1 = np.concatenate((I_1, P_1), axis=1)  # this is just a simple function to stich two matrix together
# print (G_1)

#3.2 now let's do a [15,16] "G_2 matrix" (I2|P0)
I_2 = np.eye(15, dtype=int)
# print (I_2)
P_0 = np.ones((15, 1), dtype=int) # total parity check P0 is going to Sum all the bits (d1-d11, P1-P4)
G_2 = np.concatenate((I_2, P_0), axis=1)
# print (G_2)

#3.2 the ultimate generator matrix [11,5] X [15,16] = [11,16]
G = G_1 @ G_2 %2
print ("The generator matrix:")
print (G)

# 4) Then we can generate our [1,16] output
Input = np.array([[1,0,1,1,0,0,1,1,0,1,0]])
Output = Input @ G %2
print ("The output of the hamming (16,11):")
print (Output)


The generator matrix:
[[1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]]
The output of the hamming (16,11):
[[1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1]]


#### 8) Generate the error checking matrix from G

In [50]:
# this error checking code, is basically your P matrix sitting on top of a (5x5) "eye" matrix

#We just need the "non-eye" part of the generator matrix (why?)
#                       -------------
#                       |This part  |
#[[1 0 0 0 0 0 0 0 0 0 0|1 1 0 0 1] |
# [0 1 0 0 0 0 0 0 0 0 0|1 0 1 0 1] |
# [0 0 1 0 0 0 0 0 0 0 0|0 1 1 0 1] |
# [0 0 0 1 0 0 0 0 0 0 0|1 1 1 0 0] |
# [0 0 0 0 1 0 0 0 0 0 0|1 0 0 1 1] |
# [0 0 0 0 0 1 0 0 0 0 0|0 1 0 1 1] |
# [0 0 0 0 0 0 1 0 0 0 0|1 1 0 1 0] |
# [0 0 0 0 0 0 0 1 0 0 0|0 0 1 1 1] |
# [0 0 0 0 0 0 0 0 1 0 0|1 0 1 1 0] |
# [0 0 0 0 0 0 0 0 0 1 0|0 1 1 1 0] |
# [0 0 0 0 0 0 0 0 0 0 1|1 1 1 1 1]]|
#                       |This part  |
#                       -------------
H_T = np.array([
    [1, 1, 0, 0, 1],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 0, 1],
    [1, 1, 1, 0, 0],
    [1, 0, 0, 1, 1],
    [0, 1, 0, 1, 1],
    [1, 1, 0, 1, 0],
    [0, 0, 1, 1, 1],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]
])

# next we just repeat the hamming coding trick, but on [1,16] output
# output_code: [[1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1]]
# you can inject 1 bit error below, anywhere:
received_msg = [[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1]]
Error_msg = received_msg @ H_T % 2
print ("the error code:")
print (Error_msg)

the error code:
[[1 0 0 1 1]]


#### Here are some of the quest example:

In [ ]:
data_list= [1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0]

## TODO 1: Print the total length of this data list.
# print(...)

## TODO 2: Using positive indexing, extract and print the 4th bit.
# bit_four = ...
# print(...)

## TODO 3: Using negative indexing, extract and print the very last bit.
# last_bit = ...
# print(...)

## TODO 4: Oh no, a bit flipped! Change the 1st bit (index 0) from 1 to 0, then print the list.
# ...

In [ ]:
data_list = [1, 0, 1, 1, 0]
parity_check = 0

## TODO 1: Use a 'for' loop to iterate through every bit in the data list.
## Inside the loop, use the bitwise XOR operator (^) to continuously update 'parity_check'.
# for ...
#   parity_result = ...

## TODO 2: Print the final parity_check.
# print(...)

In [ ]:
import numpy as np

## TODO 1: Create a 1D NumPy array filled with exactly 16 zeros.
# empty_array = ...
# print(empty_array)

## TODO 2: Create a 5x5 Identity matrix (a matrix with 1s on the diagonal and 0s elsewhere).
# eye_matrix = ...
# print(eye_matrix)

## TODO 3: Create a flat NumPy array with the numbers 1 through 6.
## Then, use .reshape() to turn it into a 2x3 matrix.
# flat_array = np.array([1, 2, 3, 4, 5, 6])
# reshaped_matrix = ...
# print(reshaped_matrix.shape) # Should print (2, 3)

In [ ]:
import numpy as np

# Generate the 4x8 Parity matrix for Hamming (8,4):


P = np.array([
   ?
])
# np.eye(?, dtype=int)
# np.concatenate((I, P), axis=1)

# Generate G matrix and error checking matrix H_T

Input_Data = np.array([
    [1,
     0,
     1,
     1]
])

# Perform hamming encodong and error checking on the input data.