### Traffic encoding level 3: Cloverleaf interchange

In [46]:
import numpy as np
# the way to define number array a bit different from vanilla python
lane_a = np.array([0,0,1,0,0,0,0,0,1])
lane_b = np.array([0,0,1,0,0,0,1,1,1])

collision_check = (lane_a == 1) & (lane_b ==1) # with numpy, we don't need for loop and if condition any more
print(collision_check)                         # bool

# TODO: how to turn bool return into 1 and 0? Hint: Like in spreadsheet?



[False False  True False False False False False  True]


#### Numpy array quick intro

In [21]:
# In numpy, the data array is np.array
list = [1,2,3,4]            # this is a python list, or a "python number array"
array = np.array([1,2,3,4]) # this is a numpy array, or a "numpy number array"
print(type(list))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [27]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])
print(array_1.ndim)                   # ndim is to check dimension
print(array_2.ndim)
## TODO: Can we check the dimension of a regular phyton list?

1
2


In [28]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])

print(array_1.size)                   # size is to check the total number of elements
print(array_2.size)

4
4


In [33]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([[1],[2],[3],[4]])

print(array_1.shape)                  # shape is to check the size of each dimension
print(array_2.shape)



(4,)
(4, 1)


In [38]:
array_2b = np.array([[1],
                     [2],
                     [3],
                     [4]])            # a 4x1 array in this kind of viual might be more intuitive?
print(array_2b.shape)
#print(array_2b.ndim)

(4, 1)
2


In [39]:
array_3 = array_2.reshape(1, 4)       # reshape can reshape an array
print(array_3)
print(array_3.shape)

## TODO: check what would happen if we reshape array_2 to 2x2? 2x3?

[[1 2 3 4]]
(1, 4)


In [ ]:
## TODO: make a 3D array with the size of 4
## TODO: make a 4D array with the size of 4
## TODO: make a 4D array with the size of 3

#### Indexing in numpy:

In [50]:
# numpy is also very straight forward at indexing
collision_report = np.where(collision_check == 1)     # use where, then fill in the condition (collision check =1)
print(collision_report) # why it's looking like that? Because it is a tuple of arrays.

# to turn it into a simple array, we can do this:
collision_report_array = collision_report[0]
#print (collision_report_array) ##TODO: check the result

(array([2, 8]),)


In [ ]:
# or we can do it in one go:
collision_report = np.where(collision_check == 1)[0]
#print(collision_report) ##TODO: check the result

In [54]:
lane_c = np.array([[0,0,1,0],[0,0,0,1]])
lane_d = np.array([[0,0,1,0],[0,1,1,1]])
## TODO: try collision_check and collision_report in 2D
# collsion_check_2D =
# collision_report_2D =

[[False False  True False]
 [False False False  True]]
(array([0, 1]), array([2, 3]))


#### Create an empty numpy array and populate it with numbers:

In [ ]:
# now let's use some numpy magic together

# create empty four lanes in one line of code:
I380_16A = np.zeros((4, 10), dtype=int)

print("I380 exit 16A:")
print(I380_16A)

I380 exit 16A:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
# let's put some cars in the lanes
# the following examples are just different ways we can assign values to each matrix by indexing
I380_16A[0,1] = 1
I380_16A[1,2:6] = 1
I380_16A[2,1:5] = I380_16A[1,2:6]
print("I380 exit 16A, active traffic:")
print(I380_16A)

I380 exit 16A, active traffic:
[[0 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
# Collision check, how?
# One way is to check 6 times between all the lanes
# It will be a lot of "and" and "if" though.

#### Collision check, how?
      One way is to check all 4 lanes in one go.
      One way is to check n times between all the lanes.
      It will be a lot of "and" and "if" though.

In [47]:
#Or we can encoding the lanes
# lane 0: 0b0001 = 1
# lane 1: 0b0010 = 2
# lane 2: 0b0100 = 4
# lane 3: 0b1000 = 8
# so 0b1100 = lane 3 crash with lane 2
#    0b1010 = lane 3 crash with lane 1
#    0b1001 = lane 1 crash with lane 0
#    0b0101 = ...
#    0b0110
#    0b0011
#    0b1110 = possible triple crash
#    0b0111
#    0b1011
#    0b1101
#    0b1111

In [48]:
## Next week, let's write a collision check algo that's checking collision of all lanes all the time.
